source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/adin283/PodSepcs.git'

platform :ios, '9.0'

use_frameworks!

target 'ZJYTestSDK_Example' do
  pod 'ZJYTestSDK', :path => '../'

  target 'ZJYTestSDK_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
